spring.application.name=crucible-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/crucible_db?options=-c%20TimeZone=UTC}
spring.datasource.username=${DB_USERNAME:crucible}
spring.datasource.password=${DB_PASSWORD:crucible123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Hardhat local node URL
blockchain.node.url=http://127.0.0.1:8545

# Hardhat Default Account #0 Private Key (DO NOT use this in production!)
blockchain.wallet.private-key=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80