spring.application.name=crucible-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/crucible_db?options=-c%20TimeZone=UTC
spring.datasource.username=crucible
spring.datasource.password=crucible123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update